import { useEffect } from 'react'
import { useAppStore } from '@/store/app-store'
import type { AgentSkill } from '@/store/app-store'

const BUILT_IN_SKILLS: AgentSkill[] = [
  {
    id: 'marketing-strategist',
    name: 'Marketing Strategist',
    description: 'Create comprehensive marketing plans, campaigns, and growth strategies tailored to your business goals and target audience.',
    icon: 'megaphone',
    category: 'marketing',
    prompt: 'You are an expert marketing strategist. Help users create comprehensive marketing plans, campaigns, and growth strategies.',
    isBuiltIn: true,
    usageCount: 12580,
    rating: 4.8,
    tags: 'marketing, strategy, growth, campaign',
  },
  {
    id: 'market-researcher',
    name: 'Market Researcher',
    description: 'Analyze market trends, competitive landscapes, and consumer behavior to provide actionable business intelligence.',
    icon: 'search',
    category: 'research',
    prompt: 'You are an expert market researcher. Analyze market trends, competitors, and consumer behavior to provide actionable insights.',
    isBuiltIn: true,
    usageCount: 9843,
    rating: 4.7,
    tags: 'research, market analysis, competition, trends',
  },
  {
    id: 'business-strategy',
    name: 'Business Strategy',
    description: 'Strategic planning and business analysis to help you make informed decisions and drive organizational growth.',
    icon: 'target',
    category: 'strategy',
    prompt: 'You are an expert business strategist. Provide strategic planning, business analysis, and decision-making frameworks.',
    isBuiltIn: true,
    usageCount: 8721,
    rating: 4.9,
    tags: 'strategy, planning, business, analysis',
  },
  {
    id: 'legal-analyst',
    name: 'Legal Analyst',
    description: 'Legal research and document analysis to help you understand regulations, contracts, and compliance requirements.',
    icon: 'scale',
    category: 'legal',
    prompt: 'You are an expert legal analyst. Assist with legal research, document analysis, and regulatory compliance guidance.',
    isBuiltIn: true,
    usageCount: 6450,
    rating: 4.6,
    tags: 'legal, research, compliance, documents',
  },
  {
    id: 'academic-writer',
    name: 'Academic Writer',
    description: 'Research papers, academic content, literature reviews, and scholarly writing assistance with proper citations.',
    icon: 'graduationcap',
    category: 'academic',
    prompt: 'You are an expert academic writer. Help with research papers, academic content, and scholarly writing with proper citations.',
    isBuiltIn: true,
    usageCount: 11230,
    rating: 4.8,
    tags: 'academic, research, writing, papers',
  },
  {
    id: 'content-creator',
    name: 'Content Creator',
    description: 'Blog posts, articles, social media content, and creative writing that engages your audience and drives traffic.',
    icon: 'pentool',
    category: 'writing',
    prompt: 'You are an expert content creator. Help users write engaging blog posts, articles, social media content, and creative writing.',
    isBuiltIn: true,
    usageCount: 15640,
    rating: 4.7,
    tags: 'content, writing, blog, social media',
  },
  {
    id: 'code-assistant',
    name: 'Code Assistant',
    description: 'Programming help, code review, debugging, and software development guidance across multiple languages and frameworks.',
    icon: 'code',
    category: 'development',
    prompt: 'You are an expert code assistant. Help with programming, code review, debugging, and software development guidance.',
    isBuiltIn: true,
    usageCount: 21450,
    rating: 4.9,
    tags: 'code, programming, development, debugging',
  },
  {
    id: 'data-analyst',
    name: 'Data Analyst',
    description: 'Data analysis, visualization, statistical modeling, and insights extraction from complex datasets.',
    icon: 'barchart3',
    category: 'research',
    prompt: 'You are an expert data analyst. Help with data analysis, visualization, statistical modeling, and insights extraction.',
    isBuiltIn: true,
    usageCount: 10890,
    rating: 4.7,
    tags: 'data, analysis, visualization, statistics',
  },
  {
    id: 'seo-optimizer',
    name: 'SEO Optimizer',
    description: 'SEO analysis, keyword research, on-page optimization, and strategies to improve your search engine rankings.',
    icon: 'globe',
    category: 'marketing',
    prompt: 'You are an expert SEO optimizer. Help with SEO analysis, keyword research, on-page optimization, and ranking strategies.',
    isBuiltIn: true,
    usageCount: 7890,
    rating: 4.6,
    tags: 'seo, optimization, keywords, ranking',
  },
  {
    id: 'financial-analyst',
    name: 'Financial Analyst',
    description: 'Financial modeling, investment analysis, budgeting, and comprehensive financial planning for businesses and individuals.',
    icon: 'dollarsign',
    category: 'strategy',
    prompt: 'You are an expert financial analyst. Help with financial modeling, investment analysis, budgeting, and financial planning.',
    isBuiltIn: true,
    usageCount: 9320,
    rating: 4.8,
    tags: 'finance, analysis, modeling, investment',
  },
  {
    id: 'ux-designer',
    name: 'UX Designer',
    description: 'User experience research, interface design, usability testing, and creating intuitive digital product experiences.',
    icon: 'palette',
    category: 'design',
    prompt: 'You are an expert UX designer. Help with user experience research, interface design, usability, and creating intuitive experiences.',
    isBuiltIn: true,
    usageCount: 8150,
    rating: 4.7,
    tags: 'ux, design, interface, usability',
  },
  {
    id: 'project-manager',
    name: 'Project Manager',
    description: 'Project planning, task management, timeline optimization, and team coordination for successful project delivery.',
    icon: 'kanban',
    category: 'strategy',
    prompt: 'You are an expert project manager. Help with project planning, task management, timeline optimization, and team coordination.',
    isBuiltIn: true,
    usageCount: 13670,
    rating: 4.8,
    tags: 'project, management, planning, timeline',
  },
]

export { BUILT_IN_SKILLS }

export function useInitializeStore() {
  const { skills, setSkills } = useAppStore()

  useEffect(() => {
    if (skills.length === 0) {
      setSkills(BUILT_IN_SKILLS)
    }
  }, [skills, setSkills])
}
